import Providers from '@/components/providers/app';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { Sarabun, Tajawal } from 'next/font/google';
import Header from '@/components/layout/app/header';
import Footer from '@/components/layout/app/footer';
import ReactQueryProvider from '@/components/utils/providers/react-query-provider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});
export const sarabun = Sarabun({
  subsets: ['latin', 'thai'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-sarabun',
});
export const tajawal = Tajawal({
  subsets: ['arabic'],
  weight: ['300', '400', '500', '700', '800'],
  variable: '--font-tajawal',
});

export const metadata: Metadata = {
  title: 'Rose App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased [@media(min-width:1920px)]:container [@media(min-width:1920px)]:mx-auto`}
      >
        <ReactQueryProvider>
          <Providers>
            <Header></Header>
            <div className="min-h-96">{children}</div>
            <Toaster richColors />

            <Footer></Footer>
          </Providers>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
